n = input('Digite qualquer coisa: ')
print('O tipo primitivo deste valor é', type(n))
print('Só tem espaços?', n.isspace())
print('É alfabética?', n.isalpha())
print('É um número?', n.isnumeric())
print('É alfanumérica?', n.isalnum())
print('Está em maiúscula?', n.isupper())
print('Está em minúsculas?', n.islower())
print('Está Capitalizada?', n.istitle())