nome = input('Digite seu nome: ').strip()
print('Seu nome em maiúscula é {}.'.format(nome.upper()))
print('Seu nome em minúsculas é {}.'.format(nome.lower()))
#nome = nome.split()
#nome = ''.join(nome)
print('Seu nome tem {} letras.'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome tem {} letras.'.format(len(separa[0])))